name: flutter_ai_mvp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  provider: ^6.1.2
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  camera: ^0.11.0+2
  tflite_flutter: ^0.10.4
  lottie: ^3.1.2
  material_color_utilities: ^0.11.1
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  hive_test: ^1.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true