// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_ai_mvp/test/integration/notes_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_ai_mvp/services/ai_service.dart' as _i2;
import 'package:flutter_ai_mvp/services/ai_service_manager.dart' as _i4;
import 'package:flutter_ai_mvp/services/storage_repository.dart' as _i7;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAIService_0 extends _i1.SmartFake implements _i2.AIService {
  _FakeAIService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIServiceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIServiceManager extends _i1.Mock implements _i4.AIServiceManager {
  MockAIServiceManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AIService get currentService => (super.noSuchMethod(
        Invocation.getter(#currentService),
        returnValue: _FakeAIService_0(
          this,
          Invocation.getter(#currentService),
        ),
      ) as _i2.AIService);

  @override
  bool get isServiceAvailable => (super.noSuchMethod(
        Invocation.getter(#isServiceAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Future<void> initialize({String? openAIApiKey}) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#openAIApiKey: openAIApiKey},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setOfflineService(_i2.AIService? offlineService) => super.noSuchMethod(
        Invocation.method(
          #setOfflineService,
          [offlineService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String> generateRecipe(List<String>? ingredients) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRecipe,
          [ingredients],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateRecipe,
            [ingredients],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> summarizeText(String? text) => (super.noSuchMethod(
        Invocation.method(
          #summarizeText,
          [text],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #summarizeText,
            [text],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateOpenAIApiKey(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #updateOpenAIApiKey,
          [apiKey],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HiveStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveStorageRepository<T extends _i3.HiveObject> extends _i1.Mock
    implements _i7.HiveStorageRepository<T> {
  MockHiveStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get boxName => (super.noSuchMethod(
        Invocation.getter(#boxName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#boxName),
        ),
      ) as String);

  @override
  _i5.Future<_i3.Box<T>> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _i5.Future<_i3.Box<T>>.value(_FakeBox_1<T>(
          this,
          Invocation.getter(#box),
        )),
      ) as _i5.Future<_i3.Box<T>>);

  @override
  _i5.Future<void> save(
    String? key,
    T? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            key,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T?> load(String? key) => (super.noSuchMethod(
        Invocation.method(
          #load,
          [key],
        ),
        returnValue: _i5.Future<T?>.value(),
      ) as _i5.Future<T?>);

  @override
  _i5.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<T>> loadAll() => (super.noSuchMethod(
        Invocation.method(
          #loadAll,
          [],
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> exists(String? key) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> saveAll(Map<String, T>? items) => (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [items],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, T?>> loadMultiple(List<String>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMultiple,
          [keys],
        ),
        returnValue: _i5.Future<Map<String, T?>>.value(<String, T?>{}),
      ) as _i5.Future<Map<String, T?>>);

  @override
  _i5.Future<void> deleteMultiple(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteMultiple,
          [keys],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
